--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0 (Debian 17.0-1.pgdg120+1)
-- Dumped by pg_dump version 17.0 (Debian 17.0-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO admin;

--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skins; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.skins (
    id integer NOT NULL,
    name character varying NOT NULL,
    rarity character varying,
    collection character varying,
    price character varying,
    stattrack_price character varying,
    url character varying
);


ALTER TABLE public.skins OWNER TO admin;

--
-- Name: skins_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.skins_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.skins_id_seq OWNER TO admin;

--
-- Name: skins_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.skins_id_seq OWNED BY public.skins.id;


--
-- Name: skins id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.skins ALTER COLUMN id SET DEFAULT nextval('public.skins_id_seq'::regclass);


--
-- Data for Name: goose_db_version; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.goose_db_version (id, version_id, is_applied, tstamp) FROM stdin;
1	0	t	2024-12-24 18:20:38.960417
2	20241224181039	t	2024-12-24 18:20:38.97789
\.


--
-- Data for Name: skins; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.skins (id, name, rarity, collection, price, stattrack_price, url) FROM stdin;
2	Starlight Protector	Covert\n  MP9	The Operation Riptide Collection	$1.77-$13.21	$4.87-$46.10	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_mp9_starlight_c9abe697d9.png
3	Nightwish	Covert\n  AK-47	The Operation Riptide Collection	$3.91-$50.50	$10.34-$99.96	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_ak47_nightwish_11aaa6d3f8.png
4	Melondrama	Classified\n  Dual Berettas	The Operation Riptide Collection	$0.90-$6.63	$1.21-$14.21	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_elites_beware_95d855ad44.png
5	Rapid Eye Movement	Classified\n  FAMAS	The Operation Riptide Collection	$0.88-$6.48	$1.19-$11.20	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_famas_rapid_eyes_3e09fb6644.png
6	Abyssal Apparition	Classified\n  MP7	The Operation Riptide Collection	$0.88-$6.39	$1.17-$12.09	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_mp7_fear_4664394f5a.png
7	Space Cat	Restricted\n  PP-Bizon	The Operation Riptide Collection	$0.21-$1.12	$0.27-$2.29	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_bizon_spacecat_d9191b9ef5.png
8	Dream Glade	Restricted\n  G3SG1	The Operation Riptide Collection	$0.20-$1.20	$0.28-$2.53	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_g3sg1_glade_9baad62499.png
9	Night Terror	Restricted\n  M4A1-S	The Operation Riptide Collection	$0.29-$1.19	$1.40-$4.71	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_m4a1s_insomnia_d69044a926.png
10	Zombie Offensive	Restricted\n  XM1014	The Operation Riptide Collection	$0.23-$1.10	$0.31-$2.18	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_am_xm_zombie_offensive_68090dc3bd.png
11	Ticket to Hell	Restricted\n  USP-S	The Operation Riptide Collection	$0.21-$1.25	$0.64-$4.97	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_usp_to_hell_d6e877b3ca.png
12	Scrawl	Mil-Spec Grade\n  Five-SeveN	The Operation Riptide Collection	$0.03-$0.26	$0.08-$0.96	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_fiveseven_alpha_omega_997af9c131.png
13	Ensnared	Mil-Spec Grade\n  MAC-10	The Operation Riptide Collection	$0.04-$0.21	$0.07-$0.75	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_mac10_pixie_7d573c8119.png
14	Foresight	Mil-Spec Grade\n  MAG-7	The Operation Riptide Collection	$0.04-$0.16	$0.08-$0.47	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_mag7_predictor_c27869a4a1.png
15	Necro Jr.	Mil-Spec Grade\n  MP5-SD	The Operation Riptide Collection	$0.03-$0.17	$0.07-$0.65	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_mp5_kid_necronomicon_dc90d89fa5.png
16	Lifted Spirits	Mil-Spec Grade\n  P2000	The Operation Riptide Collection	$0.03-$0.19	$0.08-$0.57	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_p2k_flying_dream_5f7815282c.png
17	Poultrygeist	Mil-Spec Grade\n  SCAR-20	The Operation Riptide Collection	$0.04-$0.15	$0.08-$0.45	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_sp_scar_chickenfight_ea2f1c9e5c.png
18	Spirit Board	Mil-Spec Grade\n  Sawed-Off	The Operation Riptide Collection	$0.03-$0.17	$0.06-$0.55	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_sawedoff_ouija_ab80d55d19.png
19	Eye of Horus	Covert\n  M4A4	The Dreams & Nightmares Collection	$111.99-$424.88	$194.80-$1,872.67	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_m4a4_ra_b2db728189.png
20	Waters of Nephthys	Classified\n  FAMAS	The Dreams & Nightmares Collection	$20.83-$65.20	$25.55-$159.77	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_famas_holo_ocean_0ece072d7f.png
21	Apep's Curse	Classified\n  P250	The Dreams & Nightmares Collection	$17.47-$56.85	$14.36-$128.54	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_p250_apep_a471d37c78.png
22	Ramese's Reach	Restricted\n  Glock-18	The Dreams & Nightmares Collection	$3.26-$11.85	$7.28-$75.19	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_glock_ramzes_b65afb4665.png
23	Sobek's Bite	Restricted\n  Nova	The Dreams & Nightmares Collection	$2.24-$7.94	$3.00-$29.38	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_nova_sobek_9b20ea74bd.png
24	ScaraB Rush	Restricted\n  P90	The Dreams & Nightmares Collection	$2.54-$7.82	$2.07-$31.77	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_p90_scarab_of_wisdom_ebb21ca107.png
25	Steel Delta	Mil-Spec Grade\n  AK-47	The Dreams & Nightmares Collection	$0.93-$2.01	$3.58-$11.29	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_ak47_strone_923af17689.png
26	Black Nile	Mil-Spec Grade\n  AWP	The Dreams & Nightmares Collection	$1.48-$4.28	$5.66-$21.00	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_awp_strone_81ef1600ee.png
27	Copper Coated	Mil-Spec Grade\n  MAG-7	The Dreams & Nightmares Collection	$0.31-$1.41	$0.12-$3.84	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_mag7_goold_435d9639f6.png
28	Mummy's Rot	Mil-Spec Grade\n  Tec-9	The Dreams & Nightmares Collection	$0.34-$1.32	$0.44-$4.97	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_tec9_mummy_74eec92f43.png
29	Mud-Spec	Industrial Grade\n  M4A1-S	The Dreams & Nightmares Collection	$0.12-$0.72	$1.00-$5.25	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_m4a1s_milspec_e4d55fb877.png
30	Echoing Sands	Industrial Grade\n  MAC-10	The Dreams & Nightmares Collection	$0.08-$0.33	$0.03-$1.04	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_mac10_scarab_cfd964346d.png
31	Azure Glyph	Industrial Grade\n  SSG 08	The Dreams & Nightmares Collection	$0.08-$0.37	$0.08-$1.33	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_ssg08_anubis_5b6f638b3a.png
32	Desert Tactical	Industrial Grade\n  USP-S	The Dreams & Nightmares Collection	$0.07-$0.44	$0.35-$2.53	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_usps_tactical_camo_1b093a1c5c.png
33	Submerged	Consumer Grade\n  M249	The Dreams & Nightmares Collection	$0.02-$0.08	$0.01-$0.09	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_m249_scarab_899cbdd1f3.png
34	Sunbaked	Consumer Grade\n  MP7	The Dreams & Nightmares Collection	$0.02-$0.10	$0.01-$0.19	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_mp7_strone_b03e2d92e6.png
35	Snake Pit	Consumer Grade\n  AUG	The Dreams & Nightmares Collection	$0.02-$0.07	$0.02-$0.18	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_hy_dune_trap_05f68e48a2.png
36	Hieroglyph	Consumer Grade\n  XM1014	The Snakebite Collection	$0.02-$0.10	$0.01-$0.34	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_xm1014_pharaoh_f903884071.png
37	Head Shot	Covert\n  AK-47	The Snakebite Collection	$4.10-$50.30	$11.08-$99.96	https://static.totalcsgo.com/totalcsgo-strapi/cu_ak_head_shot_holo_c170aa1208.png
38	Temukau	Covert\n  M4A4	The Snakebite Collection	$4.88-$96.67	$14.98-$175.00	https://static.totalcsgo.com/totalcsgo-strapi/cu_m4a4_temukau_2405f96fe0.png
39	Duality	Classified\n  AWP	The Snakebite Collection	$1.22-$10.01	$4.14-$23.41	https://static.totalcsgo.com/totalcsgo-strapi/gs_awp_limbo_snake_cb5d66e003.png
40	Wicked Sick	Classified\n  P2000	The Snakebite Collection	$1.01-$10.22	$1.45-$20.18	https://static.totalcsgo.com/totalcsgo-strapi/cu_p2000_decline_ccbb3dbede.png
41	Wild Child	Classified\n  UMP-45	The Snakebite Collection	$0.91-$9.60	$1.67-$17.96	https://static.totalcsgo.com/totalcsgo-strapi/cu_ump_clutch_kick_fa0885e164.png
42	Emphorosaur-S	Restricted\n  M4A1-S	The Snakebite Collection	$0.29-$2.18	$1.23-$7.13	https://static.totalcsgo.com/totalcsgo-strapi/cu_m4a1s_feeding_frenzy_ae3b7e4ef6.png
43	Umbral Rabbit	Restricted\n  Glock-18	The Snakebite Collection	$0.25-$1.36	$0.53-$4.07	https://static.totalcsgo.com/totalcsgo-strapi/cu_glock_moon_rabbit_2324aa3c5c.png
44	Sakkaku	Restricted\n  MAC-10	The Snakebite Collection	$0.20-$0.68	$0.58-$2.31	https://static.totalcsgo.com/totalcsgo-strapi/cu_mac10_sakkaku_d2686ea831.png
45	Banana Cannon	Restricted\n  R8 Revolver	The Snakebite Collection	$0.21-$1.57	$0.32-$3.91	https://static.totalcsgo.com/totalcsgo-strapi/gs_r8_banana_5e467b8b56.png
46	Neoqueen	Restricted\n  P90	The Snakebite Collection	$0.25-$1.27	$0.47-$2.71	https://static.totalcsgo.com/totalcsgo-strapi/gs_p90_neoqueen_c15574c58f.png
47	Insomnia	Mil-Spec Grade\n  MAG-7	The Snakebite Collection	$0.03-$0.23	$0.07-$0.75	https://static.totalcsgo.com/totalcsgo-strapi/cu_mag7_insomnia_1a0721d885.png
48	Featherweight	Mil-Spec Grade\n  MP9	The Snakebite Collection	$0.03-$0.26	$0.06-$1.12	https://static.totalcsgo.com/totalcsgo-strapi/cu_mp9_superlight_7a7540bf9b.png
49	Fragments	Mil-Spec Grade\n  SCAR-20	The Snakebite Collection	$0.03-$0.20	$0.07-$0.54	https://static.totalcsgo.com/totalcsgo-strapi/gs_scar_fragments_black_1dac5d575d.png
50	Re.built	Mil-Spec Grade\n  P250	The Snakebite Collection	$0.03-$0.25	$0.08-$0.71	https://static.totalcsgo.com/totalcsgo-strapi/cu_p250_rebuilt_910f3a0434.png
51	Liquidation	Mil-Spec Grade\n  MP5-SD	The Snakebite Collection	$0.03-$0.23	$0.08-$1.01	https://static.totalcsgo.com/totalcsgo-strapi/cu_mp5sd_quick_liquidation_262890245a.png
52	Cyberforce	Mil-Spec Grade\n  SG 553	The Snakebite Collection	$0.04-$0.25	$0.07-$0.96	https://static.totalcsgo.com/totalcsgo-strapi/cu_sg553_cyberforce_294bbf6e84.png
53	Rebel	Mil-Spec Grade\n  Tec-9	The Revolution Collection	$0.03-$0.24	$0.07-$0.85	https://static.totalcsgo.com/totalcsgo-strapi/cu_tec9_freedom_8b550b4bd6.png
54	Printstream	Covert\n  M4A1-S	The Revolution Collection	$116.75-$399.99	$167.76-$819.00	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_m4a1s_printstream_feec0c4449.png
55	Neo-Noir	Covert\n  Glock-18	The Revolution Collection	$7.62-$45.78	$26.28-$181.07	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_glock_noir_584d20a141.png
56	Fairy Tale	Classified\n  Five-SeveN	The Revolution Collection	$17.05-$47.11	$23.71-$108.87	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_five_seven_diary_146b83b3e3.png
57	Cyber Security	Classified\n  M4A4	The Revolution Collection	$14.70-$36.06	$22.89-$79.80	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_m4a4_cyberpunk_7803fb762b.png
58	Monster Mashup	Classified\n  USP-S	The Revolution Collection	$20.32-$36.39	$23.65-$78.81	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_usp_krokos_85fede152e.png
59	Exoskeleton	Restricted\n  AWP	The Revolution Collection	$2.06-$6.91	$4.42-$25.99	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_awp_exoskeleton_9bbaf6a696.png
60	Dezastre	Restricted\n  Dual Berettas	The Revolution Collection	$2.43-$5.53	$2.68-$11.44	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_dual_elites_dezastre_ac8ffa2980.png
61	Clear Polymer	Restricted\n  Nova	The Revolution Collection	$2.08-$5.47	$2.70-$10.44	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_nova_polymer_2e6114531d.png
62	Parallax	Restricted\n  SSG 08	The Revolution Collection	$2.12-$5.42	$2.49-$11.48	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_ssg08_chromatic_95b9969f62.png
63	Gold Bismuth	Restricted\n  UMP-45	The Revolution Collection	$2.15-$5.00	$2.90-$9.83	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_ump_gold_bismuth_ff8c62fe2d.png
64	Vendetta	Mil-Spec Grade\n  CZ75-Auto	The Revolution Collection	$0.46-$0.94	$0.37-$3.92	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_cz75_vendetta_09ae30671f.png
65	Cocoa Rampage	Mil-Spec Grade\n  P90	The Revolution Collection	$0.51-$0.73	$0.44-$1.90	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_hy_p90_dino_rampage_f86f436170.png
66	Digital Mesh	Mil-Spec Grade\n  G3SG1	The Revolution Collection	$0.48-$1.19	$0.44-$2.44	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_g3sg1_disrupt_87d709ded1.png
67	Vandal	Mil-Spec Grade\n  Galil AR	The Revolution Collection	$0.49-$1.37	$0.45-$4.53	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_galil_vandal_034c5b6ae9.png
68	Contaminant	Mil-Spec Grade\n  P250	The Revolution Collection	$0.49-$0.71	$0.44-$1.75	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_p250_infect_0097dc89f3.png
69	Deep Relief	Mil-Spec Grade\n  M249	The Revolution Collection	$0.48-$1.13	$0.41-$2.24	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_m249_deep_relief_e3eee6c6f4.png
70	Condition Zero	Mil-Spec Grade\n  MP5-SD	The Anubis Collection	$0.44-$1.04	$0.39-$2.89	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_mp5_conditionzero_9f55c74f2a.png
71	Chrome Cannon	Covert\n  AWP	The Anubis Collection	$18.34-$119.35	$39.04-$265.00	https://static.totalcsgo.com/totalcsgo-strapi/awp_chrome_cannon_3b60faffa5.png
72	Inheritance	Covert\n  AK-47	The Anubis Collection	$69.09-$166.00	$89.66-$395.97	https://static.totalcsgo.com/totalcsgo-strapi/ak_47_inheritance_b025baac50.png
73	Black Lotus	Classified\n  M4A1-S	The Anubis Collection	$8.25-$21.66	$20.19-$57.90	https://static.totalcsgo.com/totalcsgo-strapi/m4a1_s_black_lotus_e627d0552b.png
74	Olympus	Classified\n  Zeus x27	The Anubis Collection	$5.39-$15.42	$13.68-$37.35	https://static.totalcsgo.com/totalcsgo-strapi/zeus_x27_olympus_622318a327.png
75	Jawbreaker	Classified\n  USP-S	The Anubis Collection	$5.30-$18.00	$9.47-$51.14	https://static.totalcsgo.com/totalcsgo-strapi/usp_s_jawbreaker_50d33a17f8.png
76	Analog Input	Restricted\n  Sawed-Off	The Anubis Collection	$0.62-$2.09	$1.38-$5.00	https://static.totalcsgo.com/totalcsgo-strapi/sawed_off_analog_input_d9bba5d1ca.png
77	Just Smile	Restricted\n  MP7	The Anubis Collection	$0.61-$2.38	$1.41-$5.38	https://static.totalcsgo.com/totalcsgo-strapi/mp7_just_smile_29b3e79abb.png
78	Etch Lord	Restricted\n  M4A4	The Anubis Collection	$0.61-$2.27	$1.47-$6.64	https://static.totalcsgo.com/totalcsgo-strapi/m4a4_etch_lord_cdfc75a1c4.png
79	Block-18	Restricted\n  Glock-18	The Anubis Collection	$0.65-$2.18	$1.79-$6.33	https://static.totalcsgo.com/totalcsgo-strapi/glock_18_block_18_666babd579.png
80	Hybrid	Restricted\n  Five-SeveN	The Anubis Collection	$0.61-$2.31	$1.50-$5.90	https://static.totalcsgo.com/totalcsgo-strapi/five_seven_hybrid_3cd41c1218.png
81	Slag	Mil-Spec Grade\n  Tec-9	The Anubis Collection	$0.06-$0.28	$0.14-$0.90	https://static.totalcsgo.com/totalcsgo-strapi/tec_9_slag_05c3bd6389.png
82	Dezastre	Mil-Spec Grade\n  SSG 08	The Anubis Collection	$0.06-$0.27	$0.14-$1.46	https://static.totalcsgo.com/totalcsgo-strapi/ssg_08_dezastre_954696de51.png
83	Dark Sigil	Mil-Spec Grade\n  Nova	The Anubis Collection	$0.06-$0.24	$0.15-$0.63	https://static.totalcsgo.com/totalcsgo-strapi/nova_dark_sigil_397abc6978.png
84	Light Box	Mil-Spec Grade\n  MAC-10	The Anubis Collection	$0.05-$0.51	$0.14-$2.40	https://static.totalcsgo.com/totalcsgo-strapi/mac_10_light_box_a371069b01.png
85	Hideout	Mil-Spec Grade\n  Dual Berettas	The Anubis Collection	$0.06-$0.23	$0.14-$0.64	https://static.totalcsgo.com/totalcsgo-strapi/dual_berettas_hideout_18b96fb7d6.png
86	Irezumi	Mil-Spec Grade\n  XM1014	The Anubis Collection	$0.06-$0.25	$0.13-$0.82	https://static.totalcsgo.com/totalcsgo-strapi/xm1014_irezumi_14125af939.png
87	Motorized	Mil-Spec Grade\n  UMP-45	The Anubis Collection	$0.06-$0.25	$0.13-$0.73	https://static.totalcsgo.com/totalcsgo-strapi/ump_45_motorized_ce3d0fb508.png
88	Containment Breach	Covert\n  AWP	The Anubis Collection	$44.01-$270.90	$85.17-$593.51	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_awp_virus_314e97662b.png
89	Stalker	Covert\n  MAC-10	The Shattered Web Collection	$9.66-$51.24	$25.05-$239.99	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_mac10_stalker_3bdc329b40.png
90	Decimator	Classified\n  Tec-9	The Shattered Web Collection	$9.13-$40.90	$17.98-$122.62	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_tec9_decimator_d5581aacc7.png
91	Colony IV	Classified\n  SG 553	The Shattered Web Collection	$5.12-$30.31	$10.27-$87.90	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_sg553_reactor_92687d6b0e.png
92	Bloodshot	Classified\n  SSG 08	The Shattered Web Collection	$7.68-$57.99	$17.69-$222.00	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_ssg08_tickler_23676ec5e4.png
93	Embargo	Restricted\n  PP-Bizon	The Shattered Web Collection	$0.94-$4.28	$1.99-$12.55	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_bizon_road_warrior_150d7051e3.png
94	Rat Rod	Restricted\n  AK-47	The Shattered Web Collection	$2.38-$8.85	$8.50-$30.56	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_ak47_nibbler_1a01a4ae25.png
95	Arctic Wolf	Restricted\n  AUG	The Shattered Web Collection	$1.18-$4.28	$2.58-$14.13	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_aug_whitefang_f97ae25e17.png
96	Neon Ply	Restricted\n  MP7	The Shattered Web Collection	$0.87-$3.98	$1.85-$17.72	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_mp7_replica_7e9eee14b4.png
97	Obsidian	Restricted\n  P2000	The Shattered Web Collection	$1.04-$5.54	$2.11-$18.34	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_p2000_obsidian_5483b3ccf8.png
98	Acid Wash	Mil-Spec Grade\n  MP5-SD	The Shattered Web Collection	$0.42-$1.01	$0.54-$2.85	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_mp5_etch_41b1f09b42.png
99	Plume	Mil-Spec Grade\n  Nova	The Shattered Web Collection	$0.50-$1.04	$0.55-$3.39	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_nova_featherswing_0359fb6e00.png
100	Black Sand	Mil-Spec Grade\n  G3SG1	The Shattered Web Collection	$0.46-$0.94	$1.11-$3.02	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_g3sg1_blacksand_032dff0877.png
101	Memento	Mil-Spec Grade\n  R8 Revolver	The Shattered Web Collection	$0.45-$1.28	$0.58-$4.65	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_r8_memento_93b57161b8.png
102	Balance	Mil-Spec Grade\n  Dual Berettas	The Shattered Web Collection	$0.49-$3.11	$0.61-$10.63	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_dual_elites_rose_ed73d09adf.png
103	Torn	Mil-Spec Grade\n  SCAR-20	The Shattered Web Collection	$0.63-$0.80	$0.62-$2.14	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_sp_scar20_striker_dust_1706463bc6.png
104	Warbird	Mil-Spec Grade\n  M249	The Shattered Web Collection	$0.48-$2.54	$0.61-$3.28	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_m249_warbird_veteran_f4af694a0e.png
105	Printstream	Covert\n  USP-S	The Shattered Web Collection	$20.51-$104.96	$44.09-$223.22	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_usp_printstream_da90a31d2c.png
106	Chromatic Aberration	Covert\n  AWP	The Operation Broken Fang Collection	$5.11-$16.09	$16.40-$36.85	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_awp_chroma_pink_bfc6eb2f9d.png
107	Ice Coaled	Classified\n  AK-47	The Operation Broken Fang Collection	$3.22-$12.77	$8.54-$35.06	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_ak47_cogthings_ca9654bfc1.png
108	Visions	Classified\n  P250	The Operation Broken Fang Collection	$1.83-$8.51	$3.10-$17.68	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_p250_visions_ae8c5f4555.png
109	Kiss♥Love	Classified\n  Sawed-Off	The Operation Broken Fang Collection	$1.76-$8.97	$3.06-$19.53	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_sawedoff_kisslove_ef505421d5.png
110	Crazy 8	Restricted\n  R8 Revolver	The Operation Broken Fang Collection	$0.28-$1.66	$0.53-$4.63	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_revolver_purple_elite_4891a5ea72.png
111	Downtown	Restricted\n  M249	The Operation Broken Fang Collection	$0.25-$1.29	$0.51-$3.49	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_m249_downvote_4eb38b2d8c.png
112	Dragon Tech	Restricted\n  SG 553	The Operation Broken Fang Collection	$0.26-$1.30	$0.58-$3.48	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_sg553_cyber_dragon_2dbe348e37.png
113	Vent Rush	Restricted\n  P90	The Operation Broken Fang Collection	$0.24-$1.28	$0.54-$3.44	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_p90_tangled_a3e8f1c054.png
114	Flora Carnivora	Restricted\n  Dual Berettas	The Operation Broken Fang Collection	$0.27-$1.85	$0.52-$4.52	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_dual_elites_evil_flora_2be6dd5833.png
115	Meow 36	Mil-Spec Grade\n  FAMAS	The Operation Broken Fang Collection	$0.03-$0.20	$0.07-$0.86	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_famas_corp_meow_16f04ebd9a.png
116	Destroyer	Mil-Spec Grade\n  Galil AR	The Operation Broken Fang Collection	$0.04-$0.17	$0.10-$0.57	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_galil_destroyer_db1e2d16bd.png
117	Poly Mag	Mil-Spec Grade\n  M4A4	The Operation Broken Fang Collection	$0.04-$0.23	$0.08-$1.41	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_m4a4_elite_tactical_470e181660.png
118	Monkeyflage	Mil-Spec Grade\n  MAC-10	The Operation Broken Fang Collection	$0.03-$0.19	$0.07-$0.71	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_mac10_monkeyflage_c87645809b.png
119	Drop Me	Mil-Spec Grade\n  Negev	The Operation Broken Fang Collection	$0.03-$0.20	$0.05-$0.73	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_negev_clear_sky_91c4700e54.png
120	Roadblock	Mil-Spec Grade\n  UMP-45	The Operation Broken Fang Collection	$0.03-$0.19	$0.06-$0.60	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_ump_roadblock_f7a1e449d8.png
121	Winterized	Mil-Spec Grade\n  Glock-18	The Operation Broken Fang Collection	$0.03-$0.23	$0.10-$1.31	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_glock_elite_camo_fc5c86930a.png
122	Leet Museo	Covert\n  AK-47	The Operation Broken Fang Collection	$16.30-$72.95	$47.07-$136.79	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_ak47_abstract_5776158794.png
123	Ocean Drive	Covert\n  Desert Eagle	The Recoil Collection	$11.36-$108.56	$33.00-$343.75	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_deagle_kitch_bf077fd874.png
124	Toybox	Classified\n  MAC-10	The Recoil Collection	$2.73-$13.52	$6.23-$37.56	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_mac10_toybox_45d7a83eb4.png
125	Snack Attack	Classified\n  Glock-18	The Recoil Collection	$2.29-$15.70	$9.51-$66.11	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_glock_snackattack_44a9914008.png
126	Turbo Peek	Classified\n  SSG 08	The Recoil Collection	$4.27-$14.56	$10.83-$49.81	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_ssg_overtake_a78ed71f2e.png
127	BI83 Spectrum	Restricted\n  MAG-7	The Recoil Collection	$0.50-$1.69	$1.11-$5.93	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_mag7_bismuth_6c15434302.png
128	ZX Spectron	Restricted\n  FAMAS	The Recoil Collection	$0.76-$4.76	$2.26-$14.52	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_famas_spectron_25c4d171d8.png
129	Boost Protocol	Restricted\n  Five-SeveN	The Recoil Collection	$1.44-$3.11	$3.03-$9.51	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_five_seven_efusion_6d49edefab.png
130	Mount Fuji	Restricted\n  MP9	The Recoil Collection	$3.01-$9.49	$4.64-$26.31	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_aa_mp9_fuji_pink_2e5d1ebb3b.png
131	Spider Lily	Restricted\n  M4A4	The Recoil Collection	$2.01-$12.70	$3.37-$43.15	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_m4_flowers_8c2ea7c45b.png
132	Plague	Mil-Spec Grade\n  AUG	The Recoil Collection	$0.38-$1.15	$0.48-$2.98	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_aug_plague_f4c5143bdb.png
133	Tread	Mil-Spec Grade\n  Dual Berettas	The Recoil Collection	$0.36-$1.18	$0.47-$4.39	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_dual_berettas_tread_126863b998.png
134	Keeping Tabs	Mil-Spec Grade\n  G3SG1	The Recoil Collection	$0.47-$1.02	$0.52-$3.01	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_g3sg1_tacticalmap_4f37000a92.png
135	Guerrilla	Mil-Spec Grade\n  MP7	The Recoil Collection	$0.34-$1.74	$0.66-$3.84	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_mp7_khaki_422253ead8.png
136	Lumen	Mil-Spec Grade\n  PP-Bizon	The Recoil Collection	$0.39-$1.47	$0.50-$3.70	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_bizon_flasher_c8e28eb71a.png
137	Black Lotus	Mil-Spec Grade\n  USP-S	The Recoil Collection	$0.58-$6.21	$2.56-$26.29	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_usp_black_lotus_3550137a1a.png
138	Watchdog	Mil-Spec Grade\n  XM1014	The Recoil Collection	$0.44-$3.24	$1.11-$16.47	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_xm1014_watchdog_4e39e77bf8.png
139	The Traitor	Covert\n  USP-S	The Kilowatt Collection	$6.83-$45.59	$23.95-$155.00	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_usps_hangedman_15721940c1.png
140	In Living Color	Covert\n  M4A4	The Kilowatt Collection	$3.57-$22.47	$9.61-$68.88	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_m4a4_love_9e3e0e0afb.png
141	Food Chain	Classified\n  MP9	The Kilowatt Collection	$1.30-$8.68	$2.80-$22.45	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_mp9_food_chain_481bcbce95.png
142	Chromatic Aberration	Classified\n  Galil AR	The Kilowatt Collection	$1.26-$8.42	$2.94-$23.24	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_galil_chroma_pink_b0a4869337.png
143	XOXO	Classified\n  XM1014	The Kilowatt Collection	$1.08-$6.44	$2.03-$18.50	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_aq_xm1014_punk_d8d611cfb9.png
144	Slate	Restricted\n  AK-47	The Kilowatt Collection	$2.39-$9.86	$7.39-$35.00	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_ak47_professional_f4d298918a.png
145	dev_texture	Restricted\n  Negev	The Kilowatt Collection	$0.22-$1.10	$0.36-$2.81	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_negev_devtexture_41d11c0733.png
146	Cyber Shell	Restricted\n  P250	The Kilowatt Collection	$0.20-$1.18	$0.35-$2.76	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_p250_cybershell_a5f50e43ac.png
147	Button Masher	Restricted\n  MAC-10	The Kilowatt Collection	$0.21-$1.24	$0.31-$2.46	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_mac10_portable_76659a60d6.png
148	Trigger Discipline	Restricted\n  Desert Eagle	The Kilowatt Collection	$0.26-$2.46	$1.04-$7.99	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_deag_trigger_discipline_3e9dafd636.png
149	Circaetus	Mil-Spec Grade\n  CZ75-Auto	The Kilowatt Collection	$0.08-$0.43	$0.21-$1.75	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_cu_cz75_whirlwind_edf11e8590.png
150	Clear Polymer	Mil-Spec Grade\n  Glock-18	The Kilowatt Collection	$0.09-$1.05	$0.28-$4.23	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_glock_polymer_41fba99492.png
151	O.S.I.P.R.	Mil-Spec Grade\n  M249	The Kilowatt Collection	$0.10-$0.36	$0.25-$1.35	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_m249_combine_f7eda9efab.png
152	Junk Yard	Mil-Spec Grade\n  R8 Revolver	The Kilowatt Collection	$0.09-$0.49	$0.23-$1.73	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_r8_rustking_ea9d96ef85.png
153	Heavy Metal	Mil-Spec Grade\n  SG 553	The Kilowatt Collection	$0.09-$0.49	$0.23-$1.77	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_gs_sg553_deathmetal_6108355a4a.png
154	Oscillator	Mil-Spec Grade\n  UMP-45	The Kilowatt Collection	$0.10-$0.36	$0.24-$1.31	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_am_ump45_electrowave_d15587bf5e.png
155	Windblown	Mil-Spec Grade\n  Nova	The Kilowatt Collection	$0.12-$0.35	$0.28-$1.38	https://static.totalcsgo.com/totalcsgo-strapi/thumbnail_sp_nova_wind_dispersal_2d22360254.png
\.


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.goose_db_version_id_seq', 4, true);


--
-- Name: skins_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.skins_id_seq', 155, true);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: skins skins_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.skins
    ADD CONSTRAINT skins_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

